### ISSUE TITLE
"Click here to join the <race name> race"

### ISSUE THREAD

**Issue by LapisLettuce** [Makkuusen/TimingSystem#165]
For open events like FC2, having a feature that will send out a chat prompt to everyone on the server that they can click to enter in the current qualification or race would make events go much smoother.

Also optional: if it's possible to make it so that people already manually put in the race would not overwrite themselves when the message prompt was sent out, it would be cooler. I'm thinking about properly ordering people who pre-registered for the race and then just sending out a message afterward to anyone else who wants to join. If the people who were properly ordered won't get over written when they click on the prompt, it would be nice for them to stay in their manually positioned order.

**Comment by JustBru00** [comment]
This feature has been implemented in FrostHexHotbarItems for use on FrostHex ABG.

**Comment by Makkuusen** [comment]
Added /event broadcast clicktosign and /event broadcast clicktoreserve in #194
