### ISSUE TITLE
[New Feature] Show the gaps between every checkpoint with Verbose

### ISSUE THREAD

**Issue by Juliencool** [Makkuusen/TimingSystem#216]
There is a setting in /s where you can enable that the plugin writes the current time into the chat when you pass a checkpoint. 
The idea is a new setting or a new option for verbose which shows you the times always from one checkpoint to the next one.

**Comment by Makkuusen** [comment]
So checkpoints were created for lap validation. Verbose was originally a debug command that has been used for validating tracks. However in the future we plan to add sectors, and when implementing sectors, this will be a compelling feature to add. However I will not add any new functionality to verbose, as the goal is to move away from using it.
