### ISSUE TITLE
Upgrading from TimingSystem 1.2-RC2 to TimingSystem 1.4 doesn't work

### ISSUE THREAD

**Issue by JustBru00** [Makkuusen/TimingSystem#223]
Upgrading from TimingSystem 1.2-RC2 to TimingSystem 1.4 doesn't work.

Probably not a big deal, just wanted to note it.

**Comment by Makkuusen** [comment]
I'm guessing you might get some database error. I make sure all database updates are working automatically between major versions, however right now it only acknowledges major version. So if you install version 1.2-RC, it will update database to version 1.2. But any db changes between the 1.2 rc version and the final 1.2 release will not triggered, as the plugin will already think you are on the 1.2 version and not detect the update. You can usually hack it by removing the last update in the database version table manually before starting to trick it that you were on e.g. version 1.1. This usually works as I'm pretty sure I did include some try catch handling if you try to add a database change that is already present.

I'll see if I can either change my way of working with database updates, or to make the update system better so it is easier to keep a stable developing platform with the latest builds.

**Comment by HrKure** [comment]
I think we should start using a extra number for versioning like 1.2.2 etc. that just enumerates with every commit/pr as then it is also easier to track down what version exactly users are using when debugging or recreating errors.

**Comment by Makkuusen** [comment]
From next release and onward new issues like this one should not appear again.
