### ISSUE TITLE
What to do with language files?

### ISSUE THREAD

**Issue by Makkuusen** [Makkuusen/TimingSystem#226]
Language files are not automatically updated, meaning adding new lines requires server admin work on plugin upgrades. This is unacceptable, and has meant that newly added text has been put straight into the code instead. This means the current translation model is broken, and right now English is the only usable language.

So decisions should be made.

1. Transition everything into the code. Making english the only compatible language.

2. Transition everything to code, but make it possible to support multiple languages somehow.

3. Fix a system to properly update and manage language files, and transfer all the english currently present in code to language files instead. (And probably keep updated versions of all requested languages.)

**Comment by HrKure** [comment]
Have English as a fallback language and keep that up to date so when something does not exist in a Spanish language file get it from the English one.

**Comment by Makkuusen** [comment]
Decided to keep language files. It is possible to override the .yml files on every startup. It would make updating very easy, but it would remove the potential for people to change their own translations.
