### ISSUE TITLE
"/t set mode" time duration

### ISSUE THREAD

**Issue by SethTheLasersloth** [Makkuusen/TimingSystem#231]
It would be pretty cool if you can set the "/t set mode" to be active for only X amount of time, then it'll revert afterwards.
So, like, "/t set mode RACE <trackname> 2h" would set the track into RACE mode for 2 hours, then go back to TIMETRIAL mode afterwards.

**Comment by Makkuusen** [comment]
I've been thinking of deprecating the use these types of modes, as I have not really felt that they have been useful.

Are you ever using this to disable time trials?

**Comment by SethTheLasersloth** [comment]
I do, yes.
Although idk the difference between `/t set mode RACE` and `/t set open false` tbh. If there are hardly any, then yeah, /t set mode probably isn't that useful.

**Comment by Makkuusen** [comment]
> I do, yes. Although idk the difference between `/t set mode RACE` and `/t set open false` tbh. If there are hardly any, then yeah, /t set mode probably isn't that useful.

The difference is that closing the track hides it completely from non-admin players. It is not found in /tt, and you can't /tt to teleport to the track. Where as mode RACE only makes sure time trials doesn't start when passing the start region, but players can still access the track.
