### ISSUE TITLE
Spread out track leaderboard updates to prevent lag spikes during certain ticks

### ISSUE THREAD

**Issue by JustBru00** [Makkuusen/TimingSystem#240]
https://timings.aikar.co/dev/?id=56a95bd87ffc4ac18248aa81bd97df34

![image](https://github.com/Makkuusen/TimingSystem/assets/11063799/a339c01f-4695-4779-a4b3-3711b4b50be2)

**Comment by Makkuusen** [comment]
Yeah, this is bad. Working on it asap

**Comment by Makkuusen** [comment]
@JustBru00 Changed so it updates 1 track each tick until all tracks has been updated. There is now a service release available to download here https://github.com/Makkuusen/TimingSystem/releases/tag/1.5.1

**Comment by JustBru00** [comment]
Seems like it is working. 
![image](https://github.com/Makkuusen/TimingSystem/assets/11063799/e80ed2ec-a4ea-48c1-93dc-5de7085af576)
