### ISSUE TITLE
QualyGrid count wrong in /t info

### ISSUE THREAD

**Issue by SethTheLasersloth** [Makkuusen/TimingSystem#249]
`/t info` displays the wrong number of Qualy Grids. It writes "c ", then conveys that the # of qualy grids is the same as the # of normal grids.
Tested for both "/t info SpaFrancorchamps2023" and "/t info Hungaroring2023" in FrostHex.
![image](https://github.com/Makkuusen/TimingSystem/assets/98296847/a36bdd9b-9292-4a1c-941e-573c0cd755c9)

**Comment by Makkuusen** [comment]
Solved in 1c932ae
