### ISSUE TITLE
Track ranking function

### ISSUE THREAD

**Issue by SethTheLasersloth** [Makkuusen/TimingSystem#267]
So I think I've heard about the possibility of players being able to rank a track when time trialing it and stuff. This issue is not talking about that.
I think it might be cool to **have a function that lets drivers be able to rank the track after a race**. Then people can see their average ranking score on the /tt list. 
A possible method would be to have the message appear for them after they finish a race, saying like "On a scale of 1-10, how good was the track for racing? Click a number!" and then list a bunch of numbers for them to click. It could look something like:

On a scale of 1-10, how good was the track for racing? Click a number!
1    2    3    4    5    6    7    8    9    10

I think this would be useful because people's feedback about how a race went or how good the track was often gets missed by other players, notably the event organizers, even if the player sent messages in chat. I (Laser) totally missed what ElSaco said about Boatpark after the BRWC S7 League A race at Boatpark (Sep 16, 2023).

Although, doing this _right after the race finishes_ might not be the best, because emotions might be high at the time. At this point, it may be up to the event organizers to set up a place on the Discord for drivers to talk, which would make this function less valuable.

But I think it would be cool for each track to be able to be ranked ingame on races. I also think it might be good to separate rankings done from /event and /race, as it would be possible to "farm" good ranking on a track by using /race a bunch and having ppl rank it high. We could maybe do something like /event rankings are listed as "Competitive Race Ranking Score" and /race rankings are listed as "Fun Race Ranking Score", but then we run into the issue of fun races like Stinky Cup or Oink Oink needing to use /race to run their events for the drivers' rankings to be accurate... A possible solution would be to add a parameter to /events that makes the event creator specify if the event is for a competitive event, a casual/for fun event, or miscellaneous.

**Comment by SethTheLasersloth** [comment]
also idk how to give this issue the "feature" label so uh it might be cool if you did that for me (since I don't think I perms to do it)

**Comment by Pigalala** [comment]
Would be more idea as a seperate/private plugin, rather than part of the main plugin.
