### ISSUE TITLE
Permission for /t alltimes is not set up correctly

### ISSUE THREAD

**Issue by kazus0x27** [Makkuusen/TimingSystem#268]
Players without admin permission can only use `/t alltimes` but not  `/t alltimes` + their own name, which results in permission denied when trying to view the second page of their own times.

**Comment by Pigalala** [comment]
Redundant due to `/t mytimes`

**Comment by kazus0x27** [comment]
`/t alltimes` lists times on all tracks sorted by chronological order, while `/t mytimes` lists times on one track sorted by lap time, so they are slightly different. `/t alltimes` would be better for things like looking at consecutive lap times.
