### ISSUE TITLE
Regional OBU (OpenBoatUtils) Feature

### ISSUE THREAD

**Issue by LapisLettuce** [Makkuusen/TimingSystem#296]
Allow for regions on tracks that, when entered, changes the OBU boat mode (also have a region that can deactivate OBU in a specific area on a track and just make it vanilla racing)

In BUv420.69, we were able to use World Guard to apply effects in regions. Having this feature available in OBU, would allow for a lot of cool track gimmicks to be possible!

**Comment by Pigalala** [comment]
I believe that WorldGuard still allows for a similar behaviour but it would be nice as an official feature here. Sadly we can't add extra data to a region in TimingSystem without reworking the entire system, but imo it feels unnecesary for this single feature.

I think for now this would have to be implemented in a seperate plugin, unless a region rework to support this is planned for the future.

**Comment by Makkuusen** [comment]
I agree with Piggle, hence the issue can probably be scrapped for now.
