### ISSUE TITLE
Add ability to remove times on all tracks from a driver

### ISSUE THREAD

**Issue by ho5h1** [Makkuusen/TimingSystem#302]
Would be useful if a driver is found to be cheating.

**Comment by Pigalala** [comment]
It could be useful but it would also be a pretty dangerous command to give people. It is also possible that a cheater doesn't cheat on all tracks that they have driven on, so this command would have some bad side effects. If it is necessary to remove all times, it can be done by dropping some database entries, where it is generally limited to more trusted people who can drop them.
