### ISSUE TITLE
Custom OBU values per track

### ISSUE THREAD

**Issue by Pigalala** [Makkuusen/TimingSystem#358]
It could be an idea to allow for custom OpenBoatUtils values per track. This could open up lots of possibilities for goofy tracks and interesting mechanics, but it could also lead ice boat racing physics too far away from what it originally was.

**Comment by Makkuusen** [comment]
I'll write my thoughts as well for documentation purposes.

I currently feel a bit scared that if we normalize very custom values for each track, we might loose some of the consistency and as you state, it might turn into becoming very meme heavy.

I think the current barrier of having a specific mode implemented in openboatutils is not too large as it is. So if one has a desired mode that is different enough from the current ones we have it could go through there for now.

I however don't see any big issues with creating Add-ons to control openboatutils values for specific events. But that doesn't have to mean we natively support it for use on any track in TimingSystem. Even if we could, I don't see it as a priority atm. But that might change in the future.
