### ISSUE TITLE
Option "FORCE_BOAT" is no longer default

### ISSUE THREAD

**Issue by SethTheLasersloth** [Makkuusen/TimingSystem#366]
So I've found that the `/te option` FORCE_BOAT is not applied to the majority of tracks, now. I'm guessing that the standard default behavior has changed across TimingSystem versions.

**Is this intentional?** If it is, **do you have any recommendations on how we can fix this issue on FHex?** _(other than doing `/te option force_boat` for all like 450 tracks)_

**Comment by Makkuusen** [comment]
I'll take a look at it.
