### ISSUE TITLE
Lobby rejoin click message uses incorrect syntax

### ISSUE THREAD

**Issue by SethTheLasersloth** [Makkuusen/TimingSystem#368]
Clicking the message to rejoin the lobby after leaving it by teleporting elsewhere gives an error message, likely due to improper syntax (likely due to the implementation of the new race lobbies)
![image](https://github.com/Makkuusen/TimingSystem/assets/98296847/01adb9ff-e4e8-450c-b40c-d956589bcf64)

**Comment by Makkuusen** [comment]
Will be fixed soon, thanks for reporting it!
