### ISSUE TITLE
BoatUtils customization

### ISSUE THREAD

**Issue by 3410822385** [Makkuusen/TimingSystem#371]
Would it be possible at all to expose the plugin to more packet options such as setting the default slipperines to a different value or maybe jump force for a whole track? And beyond that maybe, setting different options to different regions in a track?

**Comment by Makkuusen** [comment]
So it is definitely possible. However I'm not personally very interested in it. I can reference my last comment I made on our discord about it. If a developer wanted to code it and make a pull request I probably wouldn't stop it from being merged though.

![image](https://github.com/Makkuusen/TimingSystem/assets/45494209/11249f30-a7be-4bd2-b355-e1c396b58e05)
