### ISSUE TITLE
Do we wanna display "IN PIT" on the scoreboard while drivers are pitting.

### ISSUE THREAD

**Issue by Makkuusen** [Makkuusen/TimingSystem#51]
Thinking of extending the pit region over the full distance. Then we could make sure scoreboard displays "IN PIT" as long as they are in the region.

Potential issues is that this might allow for people to drive into the pit, reverse out and go on the straight again. It would also allow for finishing in the pit lane on certain tracks.

**Comment by NidoThe1st** [comment]
That would be a cool addition although it doesn't seem really necessary.
If possible, you could have a region that displays IN PIT and then at some point in that region maybe have a sub-region (if possible) that would up the pit counter by one (so from 0 to 1 and from 1 to 2).
Finishing in pit lane could just be regulated by someone looking at the finish line/pitlane at the end of the race and make sure nobody does finish in the pits.

**Comment by Makkuusen** [comment]
@NidoThe1st I think actually making 2 regions exactly as you proposed can work really well. That would prevent any trickery with pit lane finish. If I make the "In pitregions" an array of any amount of regions we can make sure the pit can have "any" shape, and not just a perfect rectangle.
