### ISSUE TITLE
Quali/Race Countdown Speed/Timing

### ISSUE THREAD

**Issue by SethTheLasersloth** [Makkuusen/TimingSystem#53]
Countdown can be weird
- TechnoGustav countdown may have been delayed
- I (Laser) was testing plugin, and started a finals heat, and the countdown went by super fast (like 2x speed)

May wanna make start sequence more solid and prevent this from happening?
Should probably test more first.

**Comment by Makkuusen** [comment]
I've seen it once or twice during testing. I must admit it is a kinda weird behavior. I'm not sure there is an easy fix, but might be able to look at it in the future.

**Comment by Makkuusen** [comment]
> Countdown can be weird
> 
> * TechnoGustav countdown may have been delayed
> * I (Laser) was testing plugin, and started a finals heat, and the countdown went by super fast (like 2x speed)
> 
> May wanna make start sequence more solid and prevent this from happening? Should probably test more first.

Have we ever had this issue again?

**Comment by SethTheLasersloth** [comment]
I dont think ive seen it since
