### ISSUE TITLE
Adding players to heats more conveniently

### ISSUE THREAD

**Issue by Pigalala** [Makkuusen/TimingSystem#85]
Create a region in an area and when an event admin runs `/heat add region` (for example), all players in the region get split between all heats in the current round. Maybe also sorts the players by their time on the track.

**Comment by Makkuusen** [comment]
Could for sure be an interesting idea. For sure we need an easier way to add the people we want racing (not just everybody).

I've been thinking about sending out a join request message in chat, where people can press something like JOIN to enter the event, and automatically get placed in a heat. It would mostly achieve the same as your idea, while perhaps requiring abit less administration. Although the disadvantage is that you will not get the visual reference of who is in the region when adding them. Do you think that would achieve what you are going after with this idea?
