### ISSUE TITLE
Display Checkpoint number above/in checkpoint region when using /t edit

### ISSUE THREAD

**Issue by SethTheLasersloth** [Makkuusen/TimingSystem#93]
It'd be a neat little useful feature to display the checkpoint number over the checkpoint region, when using /t edit. For example, when you fly to the 5th checkpoint of a track, w/ /t edit on, you should be able to see the particles of the region _and_ the number 5. Can maybe be done with invisible, named armor stands, rather than trying to spell out the number with particles or something.

**Comment by Makkuusen** [comment]
In the last version you will get a popup in the actionbar when you move inside of a region. https://i.imgur.com/kPRp2DA.png

It only works if you have done /t edit <track> before. You can also use /t here to get a list of all regions you are currently standing in, if there are multiple. It's also possible to do /t tp <track> <region> to get to the spawn location of any region. Also only works with /t edit selected.

You think this would solve the issue, even if it is a different solution?

**Comment by SethTheLasersloth** [comment]
Yeah, that sounds great! Nice idea.
